version: '3'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
      - ./nerdery-app:/var/www/html
    links:
      - mysql:mysql
  mysql:
    image: "mysql:latest"
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=thenerdery
