version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nerdery_db
      - POSTGRES_PASSWORD=nerdery_password
      - POSTGRES_DB=nerdery
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
